[package]
name = "mdbook-admonish"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.14", features = ["cargo"] }
env_logger = "0.9.0"
log = "0.4.14"
mdbook = "0.4.15"
pulldown-cmark = "0.9.1"
serde_json = "1.0.79"
toml_edit = "0.13.4"

[dev-dependencies]
pretty_assertions = "1.1.0"
