[book]
authors = ["Tom Milligan"]
language = "en"
multilingual = false
src = "src"
title = "mdbook-admonish-integration"

[preprocessor]

[preprocessor.admonish]
command = "mdbook-admonish"

[output]

[output.html]
additional-css = ["././mdbook-admonish.css"]
